apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policies/security-isolation/policies.yaml
  - policies/resource-governance/policies.yaml
  - policies/image-supply-chain/policies.yaml
  - policies/networking/policies.yaml
  - policies/secrets-config/policies.yaml
  - policies/gitops-hygiene/policies.yaml
commonLabels:
  platform.example.com/component: kyverno-policies
